apiVersion: v1
kind: Template
labels:
  template: openshift-tasks-pipeline
metadata:
  name: openshift-tasks-pipeline
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-pipeline
  spec:
    source:
      type: Git
      git:
        ref: ${SOURCE_REF}
        uri: ${SOURCE_URL}
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
    - type: ConfigChange
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${PIPELINE_SCRIPT}
        env:
        - name: SOURCE_URL
          value: "${SOURCE_URL}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      type: Binary
      binary: {}
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        - name: ARTIFACT_DIR
          value: ${ARTIFACT_DIR}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: ${IMAGE_NAME}:${IMAGE_TAG}
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: openshift-tasks
- description: The name for the container image
  name: IMAGE_NAME
  required: true
  value: jboss-eap64-openshift
- description: The tag for the image
  name: IMAGE_TAG
  required: true
  value: "1.6"
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  displayName: ImageStream Namespace
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Git source URI for application
  name: SOURCE_URL
  required: true
  value: https://github.com/hashnao/openshift-tasks
- description: Git branch/tag reference
  name: SOURCE_REF
  value: master
- description: Path within Git project pointing to the pipeline run script
  name: PIPELINE_SCRIPT
  value: Jenkinsfile
- description: Maven mirror to use for S2I builds
  displayName: Maven mirror URL
  name: MAVEN_MIRROR_URL
- description: List of directories from which archives will be copied into the deployment
    folder. If unspecified, all archives in /target will be copied.
  name: ARTIFACT_DIR
- description: GitHub trigger secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
  required: true
