apiVersion: v1
kind: Template
labels:
  template: openshift-tasks-pipeline
metadata:
  name: openshift-tasks-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "${APPLICATION_NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
    labels:
      name: ${APPLICATION_NAME}-pipeline
    name: ${APPLICATION_NAME}-pipeline
  spec:
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
            try {
                timeout(time: 20, unit: 'MINUTES') {
                    node('maven') {
                        stage('build') {
                            openshiftBuild(buildConfig: '${APPLICATION_NAME}', showBuildLogs: 'true')
                        }
                        stage('deploy') {
                            openshiftDeploy(deploymentConfig: '${APPLICATION_NAME}')
                        }
                    }
                }
            } catch (err) {
                 echo "in catch block"
                 echo "Caught: ${err}"
                 currentBuild.result = 'FAILURE'
                 throw err
            }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: CzgPZAZ5m2
      type: GitHub
    - generic:
        secret: CzgPZAZ5m2
      type: Generic
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: openshift-tasks
