apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-build
    creationTimestam: null
  displayName: OpenShift Tasks - Build
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-dev
    creationTimestam: null
  displayName: OpenShift Tasks - Dev
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-prod
    creationTimestam: null
  displayName: OpenShift Tasks - Production
