kind: BuildConfig
apiVersion: v1
metadata:
  name: openshift-tasks-pipeline
spec:
  source:
    git:
      ref: ${SOURCE_REF}
      uri: ${SOURCE_URL}
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfile
    type: JenkinsPipeline
    type: Generic
  triggers:
  - github:
      secret: kJZLvfQr3hZg
    type: GitHub
  - generic:
      secret: kJZLvfQr3hZg
    type: Generic
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: openshift-tasks
- description: Git source URI for application
  name: SOURCE_URL
  required: true
  value: https://github.com/hashnao/openshift-tasks
- description: Git branch/tag reference
  name: SOURCE_REF
  value: master
