apiVersion: v1
kind: Template
labels:
  template: ${APP_NAME}-pipeline
message: Usage oc process -f jenkins-pipeline-jenkinsfilepath.yml -p GUID=$GUID | oc create -f -
metadata:
  name: ${APP_NAME}-pipeline-jenkinsfilepath
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    labels:
      name: ${APP_NAME}-pipeline-jenkinsfilepath
    name: ${APP_NAME}-pipeline-jenkinsfilepath
  spec:
    source:
      git:
        uri: ${GIT_SOURCE_URL}
        ref: ${GIT_SOURCE_REF}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${JENKINSFILE_PATH}
        env:
        - name: GUID
          value: ${GUID}
        - name: APP_NAME
          value: ${APP_NAME}
        - name: CONTEXTDIR
          value: ${CONTEXTDIR}
        - name: GIT_SOURCE_URL
          value: ${GIT_SOURCE_URL}
        - name: GIT_SOURCE_REF
          value: ${GIT_SOURCE_REF}
        - name: APP_IMAGE
          value: ${APP_IMAGE}
        - name: MAVEN_SLAVE_IMAGE
          value: ${MAVEN_SLAVE_IMAGE}
        - name: MAVEN_PATH
          value: ${MAVEN_PATH}
        - name: JENKINS_SLAVE_CPU_REQUEST
          value: ${JENKINS_SLAVE_CPU_REQUEST}
        - name: JENKINS_SLAVE_CPU_LIMIT
          value: ${JENKINS_SLAVE_CPU_LIMIT}
        - name: JENKINS_SLAVE_MEMORY_REQUEST
          value: ${JENKINS_SLAVE_MEMORY_REQUEST}
        - name: JENKINS_SLAVE_MEMORY_LIMIT
          value: ${JENKINS_SLAVE_MEMORY_LIMIT}
        - name: NEXUS_URL
          value: ${NEXUS_URL}
        - name: NEXUS_URI_MAVEN
          value: ${NEXUS_URI_MAVEN}
        - name: NEXUS_URI_PUBLIC
          value: ${NEXUS_URI_PUBLIC}
        - name: NEXUS_REGISTRY_URL
          value: ${NEXUS_REGISTRY_URL}
        - name: NEXUS_USER
          value: ${NEXUS_USER}
        - name: NEXUS_PASSWORD
          value: ${NEXUS_PASSWORD}
        - name: SONAR_URL
          value: ${SONAR_URL}
        - name: REGISTRY_URL
          value: ${REGISTRY_URL}
        jenkinsfilepath:
    triggers:
    - type: ConfigChange
parameters:
- displayName: Random GUID
  name: GUID
  value: ""
  required: true
- displayName: Application Name
  name: APP_NAME
  value: "openshift-tasks"
- displayName: Git Repository Conetext Directory
  description: Context directory of the git repository
  name: CONTEXTDIR
  value: ""
- displayName: Git Repository URL
  description: The URL of the repository with your application source code.
  name: GIT_SOURCE_URL
  value: "https://github.com/hashnao/openshift-tasks.git"
  required: true
- displayName: Git Reference
  name: GIT_SOURCE_REF
  value: master
- displayName: jenkinsfilePath
  description:
    Set "jenkins/build/Jenkinsfile" for maven build and docker build strategy.
  name: JENKINSFILE_PATH
  value: "jenkins/build/Jenkinsfile"
  required: true
- displayName: Application ImageStream
  name: APP_IMAGE
  value: "jboss-eap71-openshift:1.3"
  required: true
- displayName: Maven Custom Slave ImageStream
  name: MAVEN_SLAVE_IMAGE
  value: "jenkins-slave-appdev"
  required: true
- displayName: Maven Path
  name: MAVEN_PATH
  value: "/opt/rh/rh-maven35/root/usr/bin"
  required: true
- displayName: Jenkin Slave CPU Request
  name: JENKINS_SLAVE_CPU_REQUEST
  value: "500m"
- displayName: Jenkin Slave CPU Limit
  name: JENKINS_SLAVE_CPU_LIMIT
  value: "2"
- displayName: Jenkin Slave Memory Request
  name: JENKINS_SLAVE_MEMORY_REQUEST
  value: "1Gi"
- displayName: Jenkin Slave Memory Limit
  name: JENKINS_SLAVE_MEMORY_LIMIT
  value: "2Gi"
- displayName: Nexus Repository URL
  name: NEXUS_URL
  value: "http://nexus.${GUID}-nexus.svc:8081"
  required: true
- displayName: Nexus Repository Maven URI
  name: NEXUS_URI_MAVEN
  value: "repository/maven-releases"
  required: true
- displayName: Nexus Repository Public URI
  name: NEXUS_URI_PUBLIC
  value: "repository/maven-all-public/"
  required: true
- displayName: Nexus Registry URL
  name: NEXUS_REGISTRY_URL
  value: "docker://nexus-registry.${GUID}-nexus.svc:5000/repository/registry"
  required: true
- displayName: Nexus Username
  name: NEXUS_USER
  value: "admin"
  required: true
- displayName: Nexus Password
  name: NEXUS_PASSWORD
  value: "admin123"
  required: true
- displayName: SonarQube URL
  name: SONAR_URL
  value: "http://sonarqube.${GUID}-sonarqube.svc:9000"
  required: true
- displayName: Registry URL
  name: REGISTRY_URL
  value: "docker://docker-registry.default.svc:5000"
  required: true
